Referred doc-https://huggingface.co/docs/transformers/tasks/sequence_classification


- Show the runtime used (T4)
- Upload the financial_sentiment_data.csv file to Colab

In [ ]:
# pip install numpy==1.26.4

In [1]:
pip install evaluate

Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.0.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (2.32.4)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.12/dist-packages (from evaluate) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from evaluate) (3.7.1)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.12/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from evaluate) (1.20.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from evaluate) (26.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (3.29.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets>=2.0.0->evaluate) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (3.14.1)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.28.1)
Requirement already satisfied: typer<0.26.0,>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (0.25.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.19.0->evaluate) (2026.6.17)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->evaluate) (2026.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]>=2021.05.0->evaluate) (1.24.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (4.14.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.7.0->evaluate) (0.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.7.0->evaluate) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.7.0->evaluate) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<0.26.0,>=0.20.0->huggingface-hub>=0.7.0->evaluate) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.7.0->evaluate) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.7.0->evaluate) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26.0,>=0.20.0->huggingface-hub>=0.7.0->evaluate) (0.1.2)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 3.5 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.6

In [2]:
import numpy as np
print(np.__version__)

2.0.2

Importing required libraries

In [3]:
import numpy as np
import pandas as pd

https://www.kaggle.com/datasets/sbhatti/financial-sentiment-analysis?select=data.csv

In [4]:
financial_data = pd.read_csv("/content/financial_sentiment_data.csv")

financial_data.sample(10)

                                               Sentence Sentiment
2580                G4S slides on balance sheet worries  negative
131   Temporary lay-offs , affecting the entire work...  negative
3951  $SBUX inverted head & shoulders pattern in the...  positive
2914  Finnish M-real 's Kyro mill is starting negoti...   neutral
1597  `` This contract demonstrates our ability to a...  positive
5432  At a press conference , Lattelecom board chair...  positive
4424  The share of the share capital of both above m...   neutral
3106                                  $BBRY nice bounce  positive
3109  Marimekko Group 's full-year net sales are est...  positive
3162  The OMX Helsinki 25 index was up 0.92 pct at 2...  positive

Checking dimension of data

In [5]:
financial_data.shape

(5842, 2)

In [6]:
financial_data["Sentiment"].value_counts()

Sentiment
neutral     3130
positive    1852
negative     860
Name: count, dtype: int64

In [7]:
pd.set_option('future.no_silent_downcasting', True)

financial_data["label"] = financial_data["Sentiment"].replace({"negative": 0, "neutral": 1, "positive": 2}).astype('int64')

financial_data.sample(10)

                                               Sentence Sentiment  label
4845  The last job losses related to these reduction...   neutral      1
738   Operating profit rose to EUR 3.11 mn from EUR ...  positive      2
1810  Compared with the FTSE 100 index , which rose ...  positive      2
1610  Both operating profit and sales for the three-...  positive      2
4584  A few employees would remain at the Oulu plant...   neutral      1
5109  In 2007 , Huhtamaki will continue to invest in...   neutral      1
1364  Finnish Suominen Corporation that makes wipes ...   neutral      1
4717  Honkarakenne also decided yesterday to sell 88...   neutral      1
2338  The building will house , for example , Respec...   neutral      1
2473  Barclays Bonds Rise as Lender Cuts Dividends t...  positive      2

Converting pandas df to huggingface dataset

In [8]:
from datasets import Dataset

financial_ds = Dataset.from_pandas(financial_data)

financial_ds

Dataset({
    features: ['Sentence', 'Sentiment', 'label'],
    num_rows: 5842
})

Casts the given column as :obj:datasets.features.ClassLabel and updates the table.

In [9]:
financial_ds = financial_ds.class_encode_column("label")

Stringifying the column:   0%|          | 0/5842 [00:00<?, ? examples/s]

Casting to class labels:   0%|          | 0/5842 [00:00<?, ? examples/s]

Splitting the dataset’s  into a train and test set with the train_test_split method

In [10]:
financial_ds = financial_ds.train_test_split(test_size = 0.2, stratify_by_column = 'label', seed = 123)

financial_ds

DatasetDict({
    train: Dataset({
        features: ['Sentence', 'Sentiment', 'label'],
        num_rows: 4673
    })
    test: Dataset({
        features: ['Sentence', 'Sentiment', 'label'],
        num_rows: 1169
    })
})

Negative, positive , neutral instances can be seen

In [11]:
financial_ds['train'][1]

{'Sentence': '$YHOO A breakout above $29.83 would constitute a technical entry for the short term trader. http://stks.co/jkUF',
 'Sentiment': 'positive',
 'label': 2}

In [12]:
financial_ds['train'][2]

{'Sentence': 'New Chairman of the Board of Directors , Mr Chaim Katzman , will give a presentation and answer questions .',
 'Sentiment': 'neutral',
 'label': 1}

In [13]:
financial_ds['train'][26]

{'Sentence': '@chessNwine: $IWM 30-Minute Chart. Small caps threatening descending triangle breakdown under $110.20.  http://stks.co/r0KKm',
 'Sentiment': 'negative',
 'label': 0}

https://huggingface.co/roberta-base

NOTE that this is a model pre-trained using masked language modeling (MLM) and we are going to fine-tune it on a classification task

Here we will set up a token to access the Hugging Face hub

In [14]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("roberta-base")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Creating a preprocessing function to tokenize text and truncate sequences to be no longer than roberta-base maximum input length (512 tokens)

In [15]:
def preprocess_function(examples):
    return tokenizer(examples["Sentence"], truncation = True)

In [16]:
tokenizer.vocab_size

50265

To apply the preprocessing function over the entire dataset, use 🤗 Datasets map function. You can speed up map by setting batched=True to process multiple elements of the dataset at once:

In [17]:
tokenized_financial_ds = financial_ds.map(preprocess_function, batched = True)

Map:   0%|          | 0/4673 [00:00<?, ? examples/s]

Map:   0%|          | 0/1169 [00:00<?, ? examples/s]

In [18]:
financial_ds["train"][45]

{'Sentence': '( ADP News ) - Feb 4 , 2009 - Finnish broadband data communication systems and solutions company Teleste Oyj ( HEL : TLT1V ) said today its net profit decreased to EUR 5.5 million ( USD 7.2 m ) for 2008 from EUR 9.4 million for 200',
 'Sentiment': 'negative',
 'label': 0}

Tokenizing that instance

In [19]:
tokenized_financial_ds["train"][45]

{'Sentence': '( ADP News ) - Feb 4 , 2009 - Finnish broadband data communication systems and solutions company Teleste Oyj ( HEL : TLT1V ) said today its net profit decreased to EUR 5.5 million ( USD 7.2 m ) for 2008 from EUR 9.4 million for 200',
 'Sentiment': 'negative',
 'label': 0,
 'input_ids': [0,
  1640,
  4516,
  510,
  491,
  4839,
  111,
  1927,
  204,
  2156,
  2338,
  111,
  21533,
  11451,
  414,
  4358,
  1743,
  8,
  2643,
  138,
  5477,
  13967,
  17311,
  267,
  36,
  39509,
  4832,
  27017,
  565,
  134,
  846,
  4839,
  26,
  452,
  63,
  1161,
  1963,
  8065,
  7,
  10353,
  195,
  4,
  245,
  153,
  36,
  6775,
  262,
  4,
  176,
  475,
  4839,
  13,
  2266,
  31,
  10353,
  361,
  4,
  306,
  153,
  13,
  1878,
  2],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1]}

Detokenizing the text to get back the input text

In [20]:
tokenizer.decode(tokenized_financial_ds["train"][45]["input_ids"])

'<s>( ADP News ) - Feb 4 , 2009 - Finnish broadband data communication systems and solutions company Teleste Oyj ( HEL : TLT1V ) said today its net profit decreased to EUR 5.5 million ( USD 7.2 m ) for 2008 from EUR 9.4 million for 200</s>'

Now Creating  a batch of examples using DataCollatorWithPadding. It’s more efficient to dynamically pad the sentences to the longest length in a batch during collation, instead of padding the whole dataset to the maximum length.

In NLP, when processing sequences of text (like sentences or paragraphs), it's common to batch these sequences together for efficient training. However, since these sequences can vary in length, DataCollatorWithPadding automatically pads all sequences in a batch to match the length of the longest sequence in that batch. This ensures that all sequences in a batch have the same length, which is a requirement for most deep learning models.

In [21]:
from transformers import DataCollatorWithPadding

data_collator = DataCollatorWithPadding(tokenizer = tokenizer)

Including a metric during training is often helpful for evaluating your model’s performance. We can quickly load a evaluation method with the 🤗 Evaluate library. For this task, loading the accuracy metric.

In [22]:
import evaluate

accuracy = evaluate.load("accuracy")

Downloading builder script: 0.00B [00:00, ?B/s]

Then creating a function that passes your predictions and labels to compute to calculate the accuracy

In [23]:
def compute_metrics(eval_pred):
    predictions, labels = eval_pred
    predictions = np.argmax(predictions, axis=1)

    return accuracy.compute(predictions = predictions, references = labels)

Before you start training your model, creating a map of the expected ids to their labels with id2label and label2id.

In [24]:
id2label = {0: "negative", 1: "neutral", 2: "positive"}

label2id = {"negative": 0, "neutral": 1, "positive": 2}

In [25]:
batch_size = 16
num_epochs = 2

batches_per_epoch = len(tokenized_financial_ds["train"]) // batch_size

total_train_steps = int(batches_per_epoch * num_epochs)

In [26]:
from transformers import AutoModelForSequenceClassification
import torch

model = AutoModelForSequenceClassification.from_pretrained(
    "roberta-base", num_labels = 3, id2label = id2label, label2id = label2id
)

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
classifier.dense.weight    | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Converting train and validation datasets to the tf.data.Dataset format with prepare_tf_dataset():

Configuring the model for training with compile. Note that Transformers models all have a default task-relevant loss function, so you don’t need to specify one unless you want to

In [27]:
from transformers import TrainingArguments
from transformers import Trainer

training_args = TrainingArguments(
    output_dir="financial_sentiment_analysis",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=num_epochs,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none", # Otherwise will report to W&B
    push_to_hub=False,
)

In [28]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_financial_ds["train"],
    eval_dataset=tokenized_financial_ds["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

Write permission is validated by token
- After running the notebook cell - go to https://hf.co/oauth/device
- And paste in the code shown below

In [30]:
from huggingface_hub import notebook_login

notebook_login()

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

Train the model

In [31]:
train_result = trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Starting training our model,Calling  fit with your training and validation datasets, the number of epochs, and your callbacks to finetune the model:

https://huggingface.co/jinxxx123

In [32]:
trainer.push_to_hub("financial_text_sentiment_classification_model")

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

CommitInfo(commit_url='https://huggingface.co/jinxxx123/financial_sentiment_analysis/commit/caf707e523c6d27046c9612c18c13230d283060e', commit_message='financial_text_sentiment_classification_model', commit_description='', oid='caf707e523c6d27046c9612c18c13230d283060e', pr_url=None, repo_url=RepoUrl('https://huggingface.co/jinxxx123/financial_sentiment_analysis', endpoint='https://huggingface.co', repo_type='model', repo_id='jinxxx123/financial_sentiment_analysis'), pr_revision=None, pr_num=None)


- Go back to the model and show that the model has been pushed (make sure you refresh)
- Show the  model card, files and versions (should NOT be empty), community, and settings

In [33]:
from transformers import pipeline

text = """
  The stock market experienced significant volatility today, with the Dow Jones Industrial Average
  dropping over 500 points in early trading before recovering slightly by the close of the session.
"""

classifier = pipeline("sentiment-analysis", model = model, tokenizer = tokenizer)

classifier(text)

[{'label': 'negative', 'score': 0.5850560069084167}]

In [34]:
text = """
  The central bank announced a cut in interest rates, aiming to stimulate economic
  growth by making borrowing cheaper for both consumers and businesses.
"""

classifier(text)

[{'label': 'positive', 'score': 0.9824292659759521}]

In [35]:
text = """
  Inflation rates have been steadily increasing, prompting concerns among economists about
  the potential for reduced purchasing power and higher costs of living.
"""

classifier(text)

[{'label': 'negative', 'score': 0.5554945468902588}]

In [36]:
text = "The financial advisor recommended a balanced approach to investing, combining both growth and income strategies."

classifier = pipeline("sentiment-analysis", model = "jinxxx123/financial_sentiment_analysis")

classifier(text)

config.json:   0%|          | 0.00/898 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/388 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/3.56M [00:00<?, ?B/s]

[{'label': 'neutral', 'score': 0.8287643790245056}]

In [37]:
text = "Strong earnings reports drive the stock to new highs, boosting investor confidence."

classifier(text)

[{'label': 'positive', 'score': 0.9923412799835205}]