### Use CPU runtime

### Default model distilbert-base-uncased-finetuned-sst-2-english
* Goto https://huggingface.co/distilbert-base-uncased-finetuned-sst-2-english

In [1]:
import transformers
print(transformers.__version__)

5.12.1

In [2]:
from transformers import pipeline

help(pipeline)

Help on function pipeline in module transformers.pipelines:

pipeline(task: 'str | None' = None, model: 'str | PreTrainedModel | None' = None, config: 'str | PreTrainedConfig | None' = None, tokenizer: 'str | PreTrainedTokenizer | PreTrainedTokenizerFast | None' = None, feature_extractor: 'str | FeatureExtractionMixin | None' = None, image_processor: 'str | BaseImageProcessor | None' = None, video_processor: 'str | BaseVideoProcessor | None' = None, processor: 'str | ProcessorMixin | None' = None, revision: 'str | None' = None, use_fast: 'bool' = True, token: 'str | bool | None' = None, device: 'int | str | torch.device | None' = None, device_map: 'str | dict[str, int | str] | None' = None, dtype: 'str | torch.dtype | None' = 'auto', trust_remote_code: 'bool | None' = None, model_kwargs: 'dict[str, Any] | None' = None, pipeline_class: 'Any | None' = None, **kwargs: 'Any') -> 'Pipeline'
    Utility factory method to build a [`Pipeline`].

    A pipeline consists of:

        - One or more components for pre-processing model inputs, such as a [tokenizer](tokenizer),
        [image_processor](image_processor), [feature_extractor](feature_extractor), or [processor](processors).
        - A [model](model) that generates predictions from the inputs.
        - Optional post-processing steps to refine the model's output, which can also be handled by processors.

    <Tip>
    While there are such optional arguments as `tokenizer`, `feature_extractor`, `image_processor`, and `processor`,
    they shouldn't be specified all at once. If these components are not provided, `pipeline` will try to load
    required ones automatically. In case you want to provide these components explicitly, please refer to a
    specific pipeline in order to get more details regarding what components are required.
    </Tip>

    Args:
        task (`str`):
            The task defining which pipeline will be returned. Currently accepted tasks are:

            - `"audio-classification"`: will return a [`AudioClassificationPipeline`].
            - `"automatic-speech-recognition"`: will return a [`AutomaticSpeechRecognitionPipeline`].
            - `"depth-estimation"`: will return a [`DepthEstimationPipeline`].
            - `"document-question-answering"`: will return a [`DocumentQuestionAnsweringPipeline`].
            - `"feature-extraction"`: will return a [`FeatureExtractionPipeline`].
            - `"fill-mask"`: will return a [`FillMaskPipeline`]:.
            - `"image-classification"`: will return a [`ImageClassificationPipeline`].
            - `"image-feature-extraction"`: will return an [`ImageFeatureExtractionPipeline`].
            - `"image-segmentation"`: will return a [`ImageSegmentationPipeline`].
            - `"image-text-to-text"`: will return a [`ImageTextToTextPipeline`].
            - `"keypoint-matching"`: will return a [`KeypointMatchingPipeline`].
            - `"mask-generation"`: will return a [`MaskGenerationPipeline`].
            - `"object-detection"`: will return a [`ObjectDetectionPipeline`].
            - `"table-question-answering"`: will return a [`TableQuestionAnsweringPipeline`].
            - `"text-classification"` (alias `"sentiment-analysis"` available): will return a
              [`TextClassificationPipeline`].
            - `"text-generation"`: will return a [`TextGenerationPipeline`]:.
            - `"text-to-audio"` (alias `"text-to-speech"` available): will return a [`TextToAudioPipeline`]:.
            - `"token-classification"` (alias `"ner"` available): will return a [`TokenClassificationPipeline`].
            - `"video-classification"`: will return a [`VideoClassificationPipeline`].
            - `"zero-shot-classification"`: will return a [`ZeroShotClassificationPipeline`].
            - `"zero-shot-image-classification"`: will return a [`ZeroShotImageClassificationPipeline`].
            - `"zero-shot-audio-classification"`: will return a [`ZeroShotAudioClassificationPipeline`].
            - `"zero-shot-object-detection"`: will return a [`ZeroShotObjectDetectionPipeline`].

        model (`str` or [`PreTrainedModel`], *optional*):
            The model that will be used by the pipeline to make predictions. This can be a model identifier or an
            actual instance of a pretrained model inheriting from [`PreTrainedModel`].

            If not provided, the default for the `task` will be loaded.
        config (`str` or [`PreTrainedConfig`], *optional*):
            The configuration that will be used by the pipeline to instantiate the model. This can be a model
            identifier or an actual pretrained model configuration inheriting from [`PreTrainedConfig`].

            If not provided, the default configuration file for the requested model will be used. That means that if
            `model` is given, its default configuration will be used. However, if `model` is not supplied, this
            `task`'s default model's config is used instead.
        tokenizer (`str` or [`PreTrainedTokenizer`], *optional*):
            The tokenizer that will be used by the pipeline to encode data for the model. This can be a model
            identifier or an actual pretrained tokenizer inheriting from [`PreTrainedTokenizer`].

            If not provided, the default tokenizer for the given `model` will be loaded (if it is a string). If `model`
            is not specified or not a string, then the default tokenizer for `config` is loaded (if it is a string).
            However, if `config` is also not given or not a string, then the default tokenizer for the given `task`
            will be loaded.
        feature_extractor (`str` or [`FeatureExtractionMixin`], *optional*):
            The feature extractor that will be used by the pipeline to encode data for the model. This can be a model
            identifier or an actual pretrained feature extractor inheriting from [`FeatureExtractionMixin`].

            Feature extractors are used for non-NLP models, such as Speech or Vision models as well as multi-modal
            models. Multi-modal models will also require a tokenizer to be passed.

            If not provided, the default feature extractor for the given `model` will be loaded (if it is a string). If
            `model` is not specified or not a string, then the default feature extractor for `config` is loaded (if it
            is a string). However, if `config` is also not given or not a string, then the default feature extractor
            for the given `task` will be loaded.
        image_processor (`str` or [`BaseImageProcessor`], *optional*):
            The image processor that will be used by the pipeline to preprocess images for the model. This can be a
            model identifier or an actual image processor inheriting from [`BaseImageProcessor`].

            Image processors are used for Vision models and multi-modal models that require image inputs. Multi-modal
            models will also require a tokenizer to be passed.

            If not provided, the default image processor for the given `model` will be loaded (if it is a string). If
            `model` is not specified or not a string, then the default image processor for `config` is loaded (if it is
            a string).
        processor (`str` or [`ProcessorMixin`], *optional*):
            The processor that will be used by the pipeline to preprocess data for the model. This can be a model
            identifier or an actual processor inheriting from [`ProcessorMixin`].

            Processors are used for multi-modal models that require multi-modal inputs, for example, a model that
            requires both text and image inputs.

            If not provided, the default processor for the given `model` will be loaded (if it is a string). If `model`
            is not specified or not a string, then the default processor for `config` is loaded (if it is a string).
        revision (`str`, *optional*, defaults to `"main"`):
            When passing a task name or a string model identifier: The specific model version to use. It can be a
            branch name, a tag name, or a commit id, since we use a git-based system for storing models and other
            artifacts on huggingface.co, so `revision` can be any identifier allowed by git.
        use_fast (`bool`, *optional*, defaults to `True`):
            Whether or not to use a Fast tokenizer if possible (a [`PreTrainedTokenizerFast`]).
        token (`str` or *bool*, *optional*):
            The token to use as HTTP bearer authorization for remote files. If `True`, will use the token generated
            when running `hf auth login`.
        device (`int` or `str` or `torch.device`):
            Defines the device (*e.g.*, `"cpu"`, `"cuda:1"`, `"mps"`, or a GPU ordinal rank like `1`) on which this
            pipeline will be allocated.
        device_map (`str` or `dict[str, Union[int, str, torch.device]`, *optional*):
            Sent directly as `model_kwargs` (just a simpler shortcut). When `accelerate` library is present, set
            `device_map="auto"` to compute the most optimized `device_map` automatically (see
            [here](https://huggingface.co/docs/accelerate/main/en/package_reference/big_modeling#accelerate.cpu_offload)
            for more information).

            <Tip warning={true}>

            Do not use `device_map` AND `device` at the same time as they will conflict

            </Tip>

        dtype (`str` or `torch.dtype`, *optional*):
            Sent directly as `model_kwargs` (just a simpler shortcut) to use the available precision for this model
            (`torch.float16`, `torch.bfloat16`, ... or `"auto"`).
        trust_remote_code (`bool`, *optional*, defaults to `False`):
            Whether or not to allow for custom code defined on the Hub in their own modeling, configuration,
            tokenization or even pipeline files. This option should only be set to `True` for repositories you trust
            and in which you have read the code, as it will execute code present on the Hub on your local machine.
        model_kwargs (`dict[str, Any]`, *optional*):
            Additional dictionary of keyword arguments passed along to the model's `from_pretrained(...,
            **model_kwargs)` function.
        kwargs (`dict[str, Any]`, *optional*):
            Additional keyword arguments passed along to the specific pipeline init (see the documentation for the
            corresponding pipeline class for possible values).

    Returns:
        [`Pipeline`]: A suitable pipeline for the task.

    Examples:

    ```python
    >>> from transformers import pipeline, AutoModelForTokenClassification, AutoTokenizer

    >>> # Sentiment analysis pipeline
    >>> analyzer = pipeline("sentiment-analysis")

    >>> # Named entity recognition pipeline, passing in a specific model and tokenizer
    >>> model = AutoModelForTokenClassification.from_pretrained("dbmdz/bert-large-cased-finetuned-conll03-english")
    >>> tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-cased")
    >>> recognizer = pipeline("ner", model=model, tokenizer=tokenizer)
    ```

For public models, this warning doesn't block functionality — it's just informational.

In [3]:
sa_pipeline = pipeline("sentiment-analysis")

sa_pipeline

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

TextClassificationPipeline: {'model': 'DistilBertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [ ]:
sa_pipeline = pipeline("text-classification")

sa_pipeline

[transformers] No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f.
Using a pipeline without specifying a model name and revision in production is not recommended.

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

TextClassificationPipeline: {'model': 'DistilBertForSequenceClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [ ]:
sa_pipeline("The weather was perfect for the outdoor event, and everyone had a fantastic time.")

[{'label': 'POSITIVE', 'score': 0.9998812675476074}]

In [ ]:
sa_pipeline("I had a terrible experience with the customer service.")

[{'label': 'NEGATIVE', 'score': 0.9992349147796631}]

##### Observe this is a binary classifier ie only positive and negative

In [ ]:
sa_pipeline("The movie was fantastic and I enjoyed every moment!")

[{'label': 'POSITIVE', 'score': 0.9998898506164551}]

In [ ]:
sa_pipeline("The book was okay, nothing special.")

[{'label': 'NEGATIVE', 'score': 0.9899623394012451}]

In [ ]:
sa_pipeline([
    "Missing the deadline was incredibly disappointing, especially after all the hard work we put in.",
    "The unexpected praise from my manager really boosted my confidence.",
    "The meeting lasted exactly one hour, as scheduled.",
    "Spending time with family always fills me with joy and gratitude."
])

[{'label': 'NEGATIVE', 'score': 0.9995641112327576},
 {'label': 'POSITIVE', 'score': 0.999849796295166},
 {'label': 'NEGATIVE', 'score': 0.8796570301055908},
 {'label': 'POSITIVE', 'score': 0.9998840093612671}]

In [ ]:
print(sa_pipeline.model.config.id2label)

{0: 'NEGATIVE', 1: 'POSITIVE'}

### Using the tokenizer and model separately

##### When to use specific classes:
- You know the model architecture (e.g., you're using only BERT).
- You need access to model-specific methods or behaviors.
- You're extending or modifying the model for research.

Otherwise, the Auto* classes are preferred for general-purpose applications and code that needs to support multiple model types.

In [ ]:
from transformers import DistilBertTokenizer, DistilBertForSequenceClassification
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [ ]:
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

tokenizer

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

DistilBertTokenizer(name_or_path='distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [ ]:
tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

tokenizer

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

BertTokenizer(name_or_path='distilbert-base-uncased-finetuned-sst-2-english', vocab_size=30522, model_max_length=512, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
})

In [ ]:
model = DistilBertForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

model

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
model = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

model

Loading weights:   0%|          | 0/104 [00:00<?, ?it/s]

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [ ]:
inputs = tokenizer("The constant delays are making it difficult for us to stay motivated on this project.", return_tensors="pt")

inputs

{'input_ids': tensor([[  101,  1996,  5377, 14350,  2024,  2437,  2009,  3697,  2005,  2149,
          2000,  2994, 12774,  2006,  2023,  2622,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
logits = model(**inputs).logits

logits

tensor([[ 4.4795, -3.6257]], grad_fn=<AddmmBackward0>)

Using a negative value for the axis counts dimensions from the end of the shape, rather than the beginning. Specifically, axis=-1 refers to the last dimension of the tensor.

In [ ]:
predicted_class_id = int(logits.argmax(axis=-1)[0])

print(f"Predicted class id {predicted_class_id}")

print(f"Label {model.config.id2label[predicted_class_id]}")

Predicted class id 0
Label NEGATIVE

In [ ]:
inputs = tokenizer("Winning the competition was one of the happiest moments of my life.", return_tensors="pt")

inputs

{'input_ids': tensor([[  101,  3045,  1996,  2971,  2001,  2028,  1997,  1996,  5292,  9397,
         10458,  5312,  1997,  2026,  2166,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

In [ ]:
logits = model(**inputs).logits

logits

tensor([[-3.6673,  4.0020]], grad_fn=<AddmmBackward0>)

In [ ]:
predicted_class_id = int(logits.argmax(axis=-1)[0])

print(f"Predicted class id {predicted_class_id}")

print(f"Label {model.config.id2label[predicted_class_id]}")

Predicted class id 1
Label POSITIVE

* Goto "https://huggingface.co/"
* Click Models from the navbar
* Click "Text Classification" under NLP
* Click on cardiffnlp/twitter-roberta-base-sentiment-latest and check the page (This model classifies neutral sentiment as well)

In [ ]:
sa_pipeline = pipeline("text-classification", model="cardiffnlp/twitter-roberta-base-sentiment-latest")

sa_pipeline

config.json:   0%|          | 0.00/929 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/501M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

model.safetensors:   0%|          | 0.00/501M [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

TextClassificationPipeline: {'model': 'RobertaForSequenceClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [ ]:
print(sa_pipeline.model.config.id2label)

{0: 'negative', 1: 'neutral', 2: 'positive'}

In [ ]:
sa_pipeline("I finally completed the marathon, and the sense of accomplishment is overwhelming.")

[{'label': 'positive', 'score': 0.9842849373817444}]

In [ ]:
sa_pipeline("The meeting lasted exactly one hour, as scheduled.")

[{'label': 'neutral', 'score': 0.9426935911178589}]

In [ ]:
sa_pipeline("The book was okay, nothing special.")

[{'label': 'neutral', 'score': 0.5793184638023376}]

In [ ]:
sa_pipeline("The movie was a complete waste of time.")

[{'label': 'negative', 'score': 0.9335517883300781}]

## Emotions


* Goto "https://huggingface.co/"
* Click Models from the navbar
* Click "Text Classification" under NLP
* Click on "j-hartmann/emotion-english-distilroberta-base" and check the page (This models is trained to understand emotions)

https://huggingface.co/j-hartmann/emotion-english-distilroberta-base

In [ ]:
sa_pipeline = pipeline("text-classification", model="j-hartmann/emotion-english-distilroberta-base")

sa_pipeline

config.json:   0%|          | 0.00/1.00k [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/329M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

TextClassificationPipeline: {'model': 'RobertaForSequenceClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [ ]:
print(sa_pipeline.model.config.id2label)

{0: 'anger', 1: 'disgust', 2: 'fear', 3: 'joy', 4: 'neutral', 5: 'sadness', 6: 'surprise'}

In [ ]:
sa_pipeline("The dinner was absolutely delicious and well-prepared.")

[{'label': 'joy', 'score': 0.9052978157997131}]

In [ ]:
sa_pipeline("I felt a deep sense of sorrow when I heard about the accident.")

[{'label': 'sadness', 'score': 0.9851123690605164}]

In [ ]:
sa_pipeline("I was furious when I found out someone had lied to me.")

[{'label': 'anger', 'score': 0.9870100021362305}]

In [ ]:
sa_pipeline([
    "The smell of the spoiled food made me feel nauseous.",
    "I was quite scared walking alone in the dark alley."
])

[{'label': 'disgust', 'score': 0.8893007040023804},
 {'label': 'fear', 'score': 0.994158148765564}]

## Financial sentiment

This models is trained specific to financial news: mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis

https://huggingface.co/mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis

In [ ]:
sa_pipeline = pipeline("text-classification", model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")

sa_pipeline

config.json:   0%|          | 0.00/933 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/328M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/798k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

TextClassificationPipeline: {'model': 'RobertaForSequenceClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [ ]:
print(sa_pipeline.model.config.id2label)

{0: 'negative', 1: 'neutral', 2: 'positive'}

In [ ]:
sa_pipeline("The economic news has lifted market spirits, pushing the index up by 2%.")

[{'label': 'positive', 'score': 0.9996492862701416}]

In [ ]:
sa_pipeline([
    "The unexpected decline in consumer spending caused a negative reaction in the market, with stocks falling by 120 points.",
    "The company's strong quarterly earnings report fueled investor confidence.",
    "The company's stock remained unchanged despite the announcement of a new product launch."
])

[{'label': 'negative', 'score': 0.9988299012184143},
 {'label': 'positive', 'score': 0.9996589422225952},
 {'label': 'neutral', 'score': 0.999548614025116}]

##### We get neutral when we have statements that are not related to finance

In [ ]:
sa_pipeline("The team completed the project successfully")

[{'label': 'neutral', 'score': 0.8386051058769226}]

In [ ]:
sa_pipeline("The movie was a complete waste of time.")

[{'label': 'neutral', 'score': 0.746103048324585}]

## Zero-shot Classification

- Go to https://huggingface.co/ -> Models
- Click on Zero-shot Classification on the left pane
- Search for facebook/bart-large-mnli
- Click on the model and show the details

In [4]:
zeroshot_pipeline = pipeline("zero-shot-classification", model="FacebookAI/roberta-large-mnli")

zeroshot_pipeline

config.json:   0%|          | 0.00/688 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.43G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

[transformers] RobertaForSequenceClassification LOAD REPORT from: FacebookAI/roberta-large-mnli
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.weight | UNEXPECTED |  |
roberta.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

ZeroShotClassificationPipeline: {'model': 'RobertaForSequenceClassification', 'dtype': 'float32', 'device': 'cpu', 'input_modalities': 'text'}

In [5]:
text = "The fog crept silently through the darkened streets, swallowing the last remnants of daylight as the town braced for the unknown."

results = zeroshot_pipeline(text, candidate_labels=['romance', 'science fiction', 'horror', 'young adult', 'comedy'])

results

{'sequence': 'The fog crept silently through the darkened streets, swallowing the last remnants of daylight as the town braced for the unknown.',
 'labels': ['horror', 'young adult', 'science fiction', 'romance', 'comedy'],
 'scores': [0.5533464550971985,
  0.22838245332241058,
  0.09202351421117783,
  0.06335994601249695,
  0.06288763135671616]}

Note that the probabilities sum up to a 100%

In [6]:
import pandas as pd

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

            labels    scores
0           horror  0.553346
1      young adult  0.228382
2  science fiction  0.092024
3          romance  0.063360
4           comedy  0.062888

In [7]:
text = "The company's quarterly earnings report exceeded analysts' expectations, driving a significant uptick in stock prices."

results = zeroshot_pipeline(text, candidate_labels=['technology', 'politics', 'entertainment', 'climate change', 'business'])

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

           labels    scores
0        business  0.778561
1      technology  0.079433
2  climate change  0.064192
3   entertainment  0.041336
4        politics  0.036478

Note that the probabilities do not sum up to 1

In [8]:
text = "The proposed legislation aims to address climate change by incentivizing green energy production"
", but it has sparked fierce debate among lawmakers over its economic impact."

results = zeroshot_pipeline(text, candidate_labels=['technology', 'climate change', 'politics', 'economics', 'finance', 'business', 'environment'], multi_label=True)

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

           labels    scores
0  climate change  0.980902
1     environment  0.964392
2        politics  0.864761
3      technology  0.349934
4       economics  0.178308
5         finance  0.020369
6        business  0.011435

In [9]:
text = "As the ancient clock struck midnight, she uncovered the dusty tome that had been hidden away"
" for centuries, its pages whispering secrets of a forgotten world."

results = zeroshot_pipeline(text, candidate_labels=['gothic', 'romance', 'politics', 'comedy', 'finance', 'mystery'], multi_label=True)

df = pd.DataFrame({'labels': results['labels'], 'scores': results['scores']})

df

     labels    scores
0   mystery  0.688779
1   romance  0.609245
2    gothic  0.397447
3  politics  0.396314
4   finance  0.248854
5    comedy  0.052158